---
apiVersion: traefik.containo.us/v1alpha1
kind: TraefikService
metadata:
  name: web-canary
  namespace: default
spec:
  weighted:
    services:
      - name: whoami
        weight: 3
        port: 80
        # Optional, as it is the default value
        kind: Service
      - name: webapp-v2
        weight: 1
        port: 80
        kind: Service
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: web
  namespace: default
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`app.canary.localhost`)
      kind: Rule
      services:
      - name: web-canary
        kind: TraefikService
